language: python
python: "2.7"

virtualenv:
  system_site_packages: true

cache:
  directories:
    - lib/eco/pickle

addons:
  apt:
    packages:
    - python-sip
    - python-qt4

script:
- cd lib/eco;
- py.test
